apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: sc
spec:
  version: 8.11.1
  count: 1
  kibanaRef:
    name: sc
  config:
    apm-server:
      data_streams.enabled: false
      kibana.enabled: false
      ssl.enabled: false
      auth:
        anonymous:
          enabled: true
    output:
      elasticsearch:
        enabled: false
      kafka:
        hosts: [ "redpanda:9093" ]
        topic: 'apm'
        partition.round_robin:
          reachable_only: false
        required_acks: 1
        compression: gzip
        max_message_bytes: 10485760
  http:
    service:
      spec:
        type: LoadBalancer