apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: sc
spec:
  version: 8.11.1
  count: 1
  config:
    apm-server:
      auth:
        anonymous:
          enabled: true
      host: :8200
      kibana:
        enabled: false
      ssl:
        enabled: false
    output:
      elasticsearch:
        enabled: false
      kafka:
        compression: gzip
        hosts:
          - redpanda:9093
        max_message_bytes: 1.048576e+07
        partition:
          round_robin:
            reachable_only: false
        required_acks: 1
        topic: apm
  http:
    service:
      spec:
        type: LoadBalancer