apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: logging
  namespace: logging-system
spec:
  version: 8.11.1
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
    - name: aio
      count: 2
      podTemplate:
        spec:
          volumes:
            - name: elasticsearch-data
              emptyDir: { }
      config:
        node.roles: [ "master", "data", "ingest" ]
        xpack.ml.enabled: false
        node.store.allow_mmap: false