apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: eck
spec:
  version: 8.11.1
  nodeSets:
    - name: aio
      count: 3
      config:
        node.roles: [ "master", "data", "ingest" ]
        xpack.ml.enabled: false
        node.store.allow_mmap: false