apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: sc
spec:
  version: 8.11.1
  count: 2
  http:
    service:
      spec:
        type: LoadBalancer
        ports:
          - port: 8443
            name: https
            targetPort: 5601
  elasticsearchRef:
    name: sc
    namespace: logging-system