apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: logging
  namespace: logging-system
spec:
  version: 8.11.1
  count: 1
  http:
    service:
      spec:
        type: LoadBalancer
        ports:
          - port: 8443
            name: https
  elasticsearchRef:
    name: logging
    namespace: logging-system