apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: sc
spec:
  version: 8.11.1
  count: 1
  http:
    service:
      spec:
        type: LoadBalancer
        ports:
          - port: 5601
            name: https
  elasticsearchRef:
    name: sc
    namespace: logging-system