apiVersion: v1
kind: Secret
metadata:
  name: sc-ls-config
stringData:
  logstash.yml: |-
    api:
        http:
            host: 0.0.0.0
    config:
        reload:
            automatic: true
    pipeline:
        workers: 8
---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: sc
spec:
  count: 1
  elasticsearchRefs:
    - name: sc
      clusterName: sc
  version: 8.11.1
  configRef:
    secretName: sc-ls-config
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          kafka {
            consumer_threads => 1
            bootstrap_servers => "redpanda:9093"
            topics => [ "logs" ]
            codec => "json"
            group_id => "logstash"
            decorate_events => "extended"
            consumer_threads => "8"
          }
        }
        filter {
          if [@metadata][kafka][topic] == "logs" {
            if [kubernetes][namespace_name] {
              mutate { 
                add_field => { 
                  "[data_stream][namespace]" => "%{[kubernetes][namespace_name]}"
                }
              }
            }
          }
        }
        output {
          elasticsearch {
            hosts => [ "${SC_ES_HOSTS}" ]
            user => "${SC_ES_USER}"
            password => "${SC_ES_PASSWORD}"
            ssl_certificate_authorities => "${SC_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }